site_name: HITSZ LUG Wiki
repo_url: https://github.com/hitszlug/wiki
edit_uri: edit/main/docs/
theme:
  name: material

nav:
  - Home: index.md
  - About: about.md
  - Linux Tricks:
      - 另类好用的 Linux 命令行工具: linux-tricks/handy-cli-apps.md

extra:
  alternate:
    - name: Chinese
      link: /cn/
      lang: cn
    - name: English
      link: /en/
      lang: en
